name: movil_odoo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  shared_preferences: ^2.2.3
  http: ^1.2.1
  syncfusion_flutter_calendar: ^25.2.7+1
  image_picker: ^1.1.2
  firebase_core: ^3.1.0
  firebase_messaging: ^15.0.1
  mime: ^1.0.5
  dio: ^5.4.3+1

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/images/
